### ISSUE TITLE
Suradnja

### ISSUE THREAD

**Issue by JakovGlavac** [ChrisRoss5/e-Dnevnik-Plus#2]
Bok Kristijane,
ja sam Jakov Glavač autor [eduo instrukcija](https://instrukcije.eduo.help?utm_source=ednevnik_plus), sviđa mi se tvoj projekt eDnevnik plus i volio bih napraviti suradnju.

**Comment by ChrisRoss5** [comment]
Bok Jakove, za početak me dodaj na Discord: Ross#1570
