### ISSUE TITLE
[Suggestion] Izbor za automatsku redirekciju na ED+ app

### ISSUE THREAD

**Issue by monikapurpl3** [ChrisRoss5/e-Dnevnik-Plus#4]
Predlažem da dobijemo u postavkama izbor hoće li nas extension automatski redirektirati na web aplikaciju e-Devnik Plus-a ili da ostavimo e-Dnevnik Plus Classic kada odemo na stranicu e-Dnevnika.

**Comment by ChrisRoss5** [comment]
Kad se odabire željena verzija iz Extension Popup-a, automatski se postavlja kao zadana.
